# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('responsible_name', models.CharField(max_length=30)),
                ('test_user', models.CharField(max_length=30)),
                ('dev_user', models.CharField(max_length=30)),
                ('publish_app', models.CharField(max_length=30)),
                ('simple_desc', models.CharField(max_length=100)),
                ('other_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
